package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"fmt"
	"golang-boilerplate/ent"
	graphql1 "golang-boilerplate/graphql"
	"golang-boilerplate/model"
)

// User is the resolver for the user field.
func (r *mutationResolver) User(ctx context.Context) (*ent.UserOps, error) {
	return &ent.UserOps{}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.UserQueries, error) {
	return &model.UserQueries{}, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *ent.User) (string, error) {
	return obj.ID.String(), nil
}

// Create is the resolver for the create field.
func (r *userOpsResolver) Create(ctx context.Context, obj *ent.UserOps, input model.CreateUserInput) (*ent.User, error) {
	return r.service.User().Create(ctx, input)
}

// List is the resolver for the list field.
func (r *userQueriesResolver) List(ctx context.Context, obj *model.UserQueries, filter *ent.UserFilterInput) (*ent.UserConnection, error) {
	panic(fmt.Errorf("not implemented: List - list"))
}

// User returns graphql1.UserResolver implementation.
func (r *Resolver) User() graphql1.UserResolver { return &userResolver{r} }

// UserOps returns graphql1.UserOpsResolver implementation.
func (r *Resolver) UserOps() graphql1.UserOpsResolver { return &userOpsResolver{r} }

// UserQueries returns graphql1.UserQueriesResolver implementation.
func (r *Resolver) UserQueries() graphql1.UserQueriesResolver { return &userQueriesResolver{r} }

type userResolver struct{ *Resolver }
type userOpsResolver struct{ *Resolver }
type userQueriesResolver struct{ *Resolver }
